name: checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: install deps
      run: |
        nix develop --command bun install

    - name: pre-commit
      run: |
        nix develop --command /usr/bin/env bash -c '\
          pre-commit run \
            --all --hook-stage=manual --config ./.pre-commit-config.yaml --verbose'

    - name: unit tests
      run: |
        nix develop --command /usr/bin/env bash -c '\
          bun test -t unit- --timeout=30000'

    - name: functional tests
      run: |
        nix develop --command /usr/bin/env bash -c '\
          bun test -t func- --timeout=120000'
