name: checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: install deps
      run: |
        nix develop --command bun install

    - name: pre-commit
      run: |
        nix develop --command \
          pre-commit run \
            --all --hook-stage=manual --config ./.pre-commit-config.yaml --verbose

    - name: unit tests
      run: |
        nix develop --command \
          bun test -t unit --timeout=30000

    - name: functional tests
      run: |
        nix develop --command \
          bun test -t func --timeout=120000
